components/Pages/Pools/AllPoolsTable.tsx, components/Pages/Pools/MyPoolsTable.tsx, components/Pages/Pools/Pools.tsx, util/coinhall.ts
- add coinhall API util functions
- replace apr and 24h volume fetch logic using coinhall API
- update APR and Volume fields on pools page
=> feat: apr/24h volume feature using coinhall API

package.json, pages/api/cors.ts, util/coinhall.ts, yarn.lock
- update coinhall api logic with cors logic
=> feat: update coinhall api logic with cors logic

components/Pages/Pools/Pools.tsx
=> feat: my pools filter issue

components/Pages/Pools/AllPoolsTable.tsx, components/Pages/Pools/MyPoolsTable.tsx, components/Pages/Pools/Pools.tsx, public/mainnet/juno-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json, util/coinhall.ts
- update price calculation logic on pools
- update price decimal from 2 to 3
=> feat: fix price calculation logic on pools

components/Pages/Swap/SwapForm.tsx
- fix alignment issue of info icon on swap form
=> fix: community feedback

components/Pages/Pools/MyPoolsTable.tsx, public/mainnet/chihuahua-1/pools_list.json
=> feat: Add rHUAHUA Pool

components/Navbar/Navbar.tsx, components/Pages/ManageLiquidity/ManageLiquidity.tsx, components/Pages/NewPosition/NewPosition.tsx, components/Pages/Pools/Pools.tsx, components/Pages/Swap/Swap.tsx, components/Pages/Swap/SwapForm.tsx
=> feat:add chain info on add_liquidity/manage_liquidity features

components/Navbar/Navbar.tsx, components/Wallet/ConnectedWalletWithDisconnect/ConnectedWallet/ConnectedWalletIcon.tsx, components/Wallet/Modal/LeapConnectButton.tsx, components/Wallet/Modal/Modal.tsx, components/Wallet/Wallet.tsx, hooks/useConnectLeap.tsx, hooks/useIBCTokenBalance.tsx, hooks/useTokenBalance.tsx, services/injective.ts, state/atoms/walletAtoms.ts, types/window.d.ts, util/wallet-adapters/offlineSigningWallet.ts
integrate Leap wallet to white whale
=> leap integration

components/Pages/NewPosition/hooks/useProvideLP.ts, components/Pages/Pools/Pools.tsx, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/comdex-1/pools_list.json, public/mainnet/injective-1/pools_list.json, public/mainnet/juno-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json
Fix pools withdrawal not working
---
=> fix withdrawal on pools

public/mainnet/juno-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json
Removed pools 
- RAW-JUNO  - Juno chain
- LOOP-JUNO  - Juno chain
- LUNA-ATOM  - Juno chain
- LUNAX-LUNA  - Terra chain
- JUNO-ATOM  - Terra chain
Fixed JUNO-axlUSDC LP error on Juno chain
---
=> removed pools requested

hooks/useConnectKeplr.tsx
Fix ledger not working on keplr wallet
---
=> fix ledger not working on keplr

components/Navbar/Navbar.tsx, components/Wallet/Wallet.tsx, hooks/useTokenBalance.tsx, queries/usePoolsListQuery.ts, state/atoms/walletAtoms.ts
Fix wallet issues while switching between chains and page refresh
---
=> fix wallet issue

components/Pages/NewPosition/NewPosition.tsx, services/injective.ts, state/atoms/walletAtoms.ts
- fix tokenA and tokenB issue on new_positing route
- fix prettier error
=> fix: new_position routing issue

components/Pages/Pools/Pools.tsx, components/Wallet/Wallet.tsx, hooks/useTokenBalance.tsx, hooks/useTradingHistory.ts, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/comdex-1/pools_list.json, public/mainnet/injective-1/pools_list.json, public/mainnet/juno-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json, util/wallet-adapters/offlineSigningWallet.ts
- fix injective apr value based on dynamic swap fee
- fix lp provide issue
- fix injective keplr connect issure
=> feat: injective apr based on dynamic swap fee

components/Wallet/ChainSelect/ChainList/ChainItem.tsx, components/Wallet/ChainSelect/ChainList/ChainList.tsx, hooks/useChainInfo.ts, hooks/useTerraStation.tsx, hooks/useTokenBalance.tsx
Use cosmos directory rest while fixing issue, update prefix for luna and remove comdex +injective configs for now
---
=> fix(Station): Update REST URLs, handle testing issues  

components/Wallet/Wallet.tsx
=> fix looping issue

components/Pages/ManageLiquidity/ManageLiquidity.tsx, components/Pages/NewPosition/NewPosition.tsx, components/Pages/Pools/Pools.tsx, components/Vaults/ManagePoistion/ManagePosition.tsx, components/Vaults/NewPosition.tsx, components/Vaults/hooks/useVaults.tsx, components/Wallet/Wallet.tsx, netlify.toml, next.config.js, public/mainnet/phoenix-1/pools_list.json, queries/tokenToTokenPriceQuery.ts, queries/useGetTokenDollarValueQuery.ts, queries/useQueryPools.ts
- Fixed page looping
- Default to Terra as discussed on chat
- Pull token price from coingecko if not available derive from pool
---
=> Fix prod reported issues

components/Pages/NewPosition/NewPositionForm.tsx, components/Pages/Pools/MyPoolsTable.tsx, components/Pages/Pools/Pools.tsx, components/Pages/Pools/components/MyPosition.tsx, public/mainnet/phoenix-1/pools_list.json
- fix my position dollar value
- updated my position tooltip with individual amount
---
=> fix my position invalud values

.prettierrc.json, components/Pages/NewPosition/hooks/useProvideLP.ts, components/Pages/Pools/Pools.tsx, components/Pages/Pools/components/TotalLiq.tsx, hooks/useTokenDollarValue.tsx, package.json, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/juno-1/pools_list.json, queries/tokenDollarValueQuery/fetchDollarPriceByTokenIds.ts, queries/useGetTokenDollarValueQuery.ts, tsconfig.json, yarn.lock
=> feat(pools): Add ampWHALE-WHALE, bWHALE-WHALE, WHALE-HUAHUA

components/Navbar/NavMenu.json, components/Navbar/Navbar.tsx, components/Navbar/NavbarPopper.tsx
Directs user to page https://tfm.com/bridge
Added NavbarPoppers for avoiding space issues
---
=> feat(tfm-bridge): added bridge Navbar button

public/mainnet/chihuahua-1/pools_list.json, public/mainnet/comdex-1/pools_list.json, public/mainnet/injective-1/pools_list.json, public/mainnet/juno-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json, queries/tokenDollarValueQuery/fetchDollarPriceByTokenIds.ts, queries/useGetTokenDollarValueQuery.ts
=> fix whale price

components/Pages/Dashboard/hooks/getClaimableEpochs.ts
Epochs in list were in reversed order
---
=> fix(bonding-apr): fixed calculation

.husky/pre-commit, components/Pages/Incentivize/hooks/useIncentivePoolInfo.ts, components/Pages/Liquidity/AvailableRewards.tsx, components/Pages/Liquidity/ManageLiquidity.tsx, components/Pages/Liquidity/Rewards.tsx, components/Pages/Liquidity/hooks/useRewards.ts, features/liquidity/components/SegmentedRewardsSimulator.tsx, package.json, yarn.lock
=> fix(daily-estimated-rewards): were not displayed correctly

constants/bonding_contract.ts
=> feature(chihuahua-incentives): enabling incentives for chihuahua

components/Pages/BondingActions/hooks/useTransaction.tsx, util/enigma.ts
=> fix(coinhall-api): integrated new api endpoint

components/Pages/Pools/Pools.tsx, pages/_app.tsx, public/logs.js
=> feat(debug-logs): enabled debug logs when typing logs() in console

public/mainnet/chihuahua-1/pools_list.json, public/mainnet/juno-1/pools_list.json
=> feat(rac): Add WHALE-RAC pools to both chihuahua and juno

public/mainnet/juno-1/pools_list.json
=> fix(rac-denom-juno): replaced with correct denom

public/mainnet/juno-1/pools_list.json
=> feat(rac): Update WHALE-RAC info

public/mainnet/juno-1/pools_list.json
=> fix(pools): Update pools list

public/mainnet/migaloo-1/config.json
=> fix(adding-sc-addresses). fe helper and incentive factory for migaloo

public/mainnet/migaloo-1/pools_list.json
=> feat(whale-axlusdc-migaloo): added whale-axlusdc pool

queries/useQueryPoolsLiquidity.ts
=> fix(handle-denom): handling of arbWhale denoms not matching

components/Pages/BondingActions/hooks/useTransaction.tsx, components/Pages/Liquidity/hooks/createLPMsg.ts, components/Pages/Liquidity/hooks/useDepositTransaction.tsx
=> fix(invalid-coins): denoms sorted in funds parameter

public/mainnet/phoenix-1/pools_list.json
=> fix(whale-luna-incentiveAddress): added address

components/Navbar/NavbarPopper.tsx
=> chore: icons for navbar

components/Pages/Incentivize/hooks/useIncentivePoolInfo.ts, components/Pages/Pools/Pools.tsx
Past flow data was not properly filtered out
---
=>  fix(incentive-logo): some logos did not appear

components/Pages/Pools/MyPoolsTable.tsx, components/Pages/Pools/components/Apr.tsx, components/Pages/Pools/components/liquidity.tsx
=> fix: liquidity tooltip

components/Pages/Swap/Swap.tsx
=> Fix swap deeplinks

components/Pages/Trade/Liquidity/Action.tsx, components/Pages/Trade/Liquidity/Positions.tsx, components/Pages/Trade/Liquidity/hooks/useLockedPositions.ts, components/Pages/Trade/Liquidity/hooks/useWithdrawPosition.ts
=> fix(withdraw-locked-pos): enabled unlock locked lp

components/Pages/Trade/Liquidity/Multiplicator.tsx, public/mainnet/chain_info.json, services/treasuryService.ts, util/enigma.ts
=> fix(terra-classic): fcd, rpc and lcd endpoints changed

components/Pages/Dashboard/BondingActions/hooks/bondTokens.ts, components/Pages/Dashboard/BondingActions/hooks/unbondTokens.ts, components/Pages/Dashboard/BondingActions/hooks/withdrawTokens.ts
=> fix: bond unbond terrac

components/Wallet/Modal/WalletConnectButton.tsx
=> fix: add missing chains to keplr

components/AssetInput/AssetInput.tsx, components/AssetInput/WhaleInput.tsx, components/Pages/Dashboard/BondingOverview.tsx, components/Pages/Dashboard/Dashboard.tsx, components/Pages/Dashboard/RewardsComponent.tsx, components/Pages/Trade/Incentivize/hooks/useClosePosition.ts, components/Pages/Trade/Swap/defaultTokens.json, components/Wallet/ChainSelect/NetworkForm/NetworkSwitch.tsx, components/Wallet/ChainSelectWithBalance/ChainSelectWithBalance.tsx, components/Wallet/ConnectedWalletWithDisconnect/ConnectedWallet/ConnectedWallet.tsx, components/Wallet/ConnectedWalletWithDisconnect/ConnectedWallet/ConnectedWalletIcon.tsx, components/Wallet/ConnectedWalletWithDisconnect/ConnectedWalletWithDisconnect.tsx, components/Wallet/Wallet.tsx, constants/networks.ts, hooks/useClients.ts, next-env.d.ts, pages/[chainId]/swap.tsx, public/testnet/narwhal-1/pools_list.json, state/chainState.ts
Retrieved chain from browser window object
Adjusted testnet connection
Reworked loading component on Dashboard.tsx
---
=> fix(chain-url-param): restructured Wallet.tsx

components/Pages/Dashboard/BondingActions/BondingActionTooltip.tsx, components/Pages/Dashboard/RewardsComponent.tsx, components/Pages/Dashboard/RewardsTooltip.tsx
=> fix(show-reward-tooltip): removed label state mamnagement

components/Pages/Trade/Liquidity/ManageLiquidity.tsx, components/Wallet/Wallet.tsx
=> fix(manage-liquidity-url-poolId): debug statement

components/Pages/Flashloan/FlashloanForm.tsx, components/Pages/Flashloan/Vaults/hooks/createDepositMsgs.ts, components/Pages/Flashloan/Vaults/hooks/useDeposit.tsx, public/mainnet/phoenix-1/pools_list.json
=> feat(ampRoar-Roar-pool): added specifications

constants/signerOptions.ts
=> fix: terra station fees

public/mainnet/phoenix-1/pools_list.json
for ampROAR-ROAR and update WHALE-LUNA
DO NOT MERGE YET
---
=> chore: add incentive contracts roar/amproar whale/luna

components/Pages/Dashboard/Dashboard.tsx, components/Pages/Dashboard/RewardsComponent.tsx, components/Pages/Dashboard/hooks/getGlobalIndex.ts, components/Pages/Dashboard/hooks/useDashboardData.ts
=> fix for dashboard APR

public/mainnet/migaloo-1/pools_list.json
=> fix(pool): ampMNTA-WHALE

components/Pages/Dashboard/BondingActions/BondingActions.tsx, components/Pages/Dashboard/BondingActions/Withdraw.tsx, components/Pages/Dashboard/BondingActions/hooks/useTransaction.tsx, components/Pages/Dashboard/hooks/getGlobalIndex.ts, components/Pages/Dashboard/hooks/getWithdrawable.ts, components/Pages/Trade/Swap/hooks/useTransaction.tsx, hooks/useRefetchQueries.ts, hooks/useTxInfo.ts, hooks/useTxStatus.tsx
=> fix(withdraw-amount): adjusted amount conversion

.github/CODEOWNERS
=> fix(codeowners): Update codeowners

components/AssetInput/BalanceWithMax.tsx, hooks/useCoinGecko.ts, pages/api/coingecko.ts, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/columbus-5/pools_list.json, queries/tokenDollarValueQuery/fetchDollarPriceByTokenIds.ts
=> fix(coingecko-geo-blocking): routing via our server

components/Pages/Dashboard/BondingActions/hooks/bondTokens.ts, components/Pages/Dashboard/BondingActions/hooks/claimRewards.ts, components/Pages/Dashboard/BondingActions/hooks/createNewEpoch.ts, components/Pages/Dashboard/BondingActions/hooks/unbondTokens.ts, components/Pages/Dashboard/BondingActions/hooks/withdrawTokens.ts, components/Pages/Trade/Incentivize/hooks/useClosePosition.ts, components/Pages/Trade/Incentivize/hooks/useOpenFlow.ts, components/Pages/Trade/Liquidity/hooks/useClaim.ts, components/Pages/Trade/Liquidity/hooks/useClosePosition.ts, components/Pages/Trade/Liquidity/hooks/useForceEpochAndTakingSnapshots.ts, components/Pages/Trade/Liquidity/hooks/useWithdrawPosition.ts, components/Pages/Trade/Liquidity/hooks/useWithdrawTransaction.tsx, components/Pages/Trade/Swap/hooks/directTokenSwap.ts, package.json, services/liquidity/executeAddLiquidity.ts, services/treasuryService.ts
Only pay extra fees if Lunc is in funds, no need to send any other token. --> See error message.
remove feather.js
add exception for creating flow before daily epoch
Tested swapping, deposit liquidity, Bonding Dashboard all Actions, etc. **Open flow not tested** 
Error: Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 
"2383ibc/077EE5F87CE5CD419436D26533329BDC7BEE6850AD64BC316486B0DCCB13C0EB", required: "1435345uaud,1435345ucad,1057623uchf,7403357ucny,6799001udkk,944306ueur,830989ugbp,8838701uhkd,16468690100uidr,82192362uinr,123666265ujpy,1284255650ukrw,43295931uluna,3237616049umnt,4532667umyr,9443057unok,57413782uphp,792749usdr,9443057usek,1510889usgd,34901536uthb,30217780utwd,1133167uusd" = …
=> feat/rework Terra Classic Fees

components/Pages/Trade/Incentivize/hooks/useIncentivePoolInfo.ts, components/Pages/Trade/Pools/AllPoolsTable.tsx, components/Pages/Trade/Pools/MobilePools.tsx, components/Pages/Trade/Pools/MyPoolsTable.tsx, components/Pages/Trade/Pools/Pools.tsx, components/Pages/Trade/Pools/components/Apr.tsx, state/aprHelperState.ts, util/conversion/numberUtil.ts, util/enigma.ts
=> fix(table-sorting): reworked table sorting

components/Wallet/Modal/WalletConnectButton.tsx
=> fix(renaming): terra station -> station

components/Pages/Dashboard/RewardsComponent.tsx, components/Pages/Trade/Pools/AllPoolsTable.tsx
=> fix: dashboard claim

components/Pages/Dashboard/BondingActions/hooks/useTransaction.tsx
=> chore: error message on pending epochs

services/liquidity/executeAddLiquidity.ts
=> fix: readd broadcast

components/Layout/RadialGradient.tsx
=> feat(juno-bg): adjusted juno bg

components/Pages/Trade/Pools/AllPoolsTable.tsx, components/Pages/Trade/Pools/components/Liquidity.tsx
=> fix(pools-width): fixed width

components/Pages/Trade/Swap/hooks/useRoute.ts
=> chore: null if no price data

public/mainnet/migaloo-1/pools_list.json
=> chore: added incentive address guppy-ash

components/Pages/Trade/Pools/AllPoolsTable.tsx, components/Pages/Trade/Pools/components/Liquidity.tsx, public/mainnet/injective-1/pools_list.json, services/poolDataProvider.ts
=> feat(inj-whale-pool): adding pool config

components/Pages/Trade/Pools/MyPoolsTable.tsx
=> fix(my-pools-table): refactoring

components/Pages/Trade/Incentivize/IncentivePositionsOverview.tsx, components/Pages/Trade/Liquidity/Positions.tsx
=> chore: add dropdowns for incentive overview + positions

components/Pages/Dashboard/hooks/useDashboardData.ts, constants/networks.ts, hooks/useClients.ts, public/mainnet/injective-1/config.json
=> chore: add inj

components/Finder.tsx, components/Pages/Trade/Liquidity/hooks/useWithdrawTransaction.tsx, components/Pages/Trade/Swap/hooks/useTransaction.tsx, components/Wallet/Wallet.tsx, hooks/useTxInfo.ts
=> fix(swap-symbols): fixed spelling

constants/signerOptions.ts
=> update terra2 gasprice

components/InfoTooltip.tsx, components/Pages/Trade/Incentivize/IncentivePositionsOverview.tsx, components/Pages/Trade/Incentivize/Incentivize.tsx, components/Pages/Trade/Liquidity/Multiplicator.tsx, components/Pages/Trade/Pools/Incentives.tsx, components/Pages/Trade/Pools/IncentivesLogos.tsx
=> fix(incentive-icons): ensured that logos are circular

components/Pages/Trade/Incentivize/hooks/useIncentivePoolInfo.ts
=> fix(incentive-apr): dynamic decimals

components/Pages/Trade/Incentivize/IncentivePositionsOverview.tsx
=> incentives amount decimals

constants/signerOptions.ts
=> terra fees back to normal

components/Pages/Trade/Pools/Pools.tsx
=> fix(incentives-apr): show correct apr in deposit form

public/mainnet/migaloo-1/pools_list.json
=> add guppy-whale pool

components/Pages/Trade/Pools/Pools.tsx
=> fix(client-exception): making apr null safe

components/Navbar/NavbarPopper.tsx
=> chore: dashboard link access

components/AssetInput/AssetList.tsx, components/Layout/AppLayout.tsx, components/Pages/Dashboard/BondingActions/hooks/bondTokens.ts, components/Pages/Dashboard/BondingActions/hooks/claimRewards.ts, components/Pages/Dashboard/BondingActions/hooks/createNewEpoch.ts, components/Pages/Dashboard/BondingActions/hooks/useTransaction.tsx, components/Pages/Dashboard/BondingActions/hooks/withdrawTokens.ts, components/Pages/Dashboard/Dashboard.tsx, components/Pages/Dashboard/hooks/getBonded.ts, components/Pages/Dashboard/hooks/getUnbonding.ts, components/Pages/Dashboard/hooks/getWithdrawable.ts, components/Pages/Dashboard/hooks/useDashboardData.ts, components/Pages/Trade/Incentivize/IncentivePositionsOverview.tsx, components/Pages/Trade/Liquidity/Overview.tsx, components/Pages/Trade/Liquidity/Positions.tsx, components/Pages/Trade/Liquidity/hooks/createLPMsg.ts, components/Wallet/ChainSelect/ChainList/ChainItem.tsx, constants/networks.ts, hooks/useClients.ts, hooks/useTokenBalance.tsx, pages/_app.tsx, util/parseError.ts
+ avoid blockin cosmoskit connect error
+ lint
+ add error messages
---
=> Bonding Tokensymbol + CosmosKit wallet reorder + Error messages

components/Pages/Trade/Liquidity/hooks/createLPMsg.ts
=> chore: increase slippage

components/Pages/Trade/Swap/SwapForm.tsx, components/Pages/Trade/Swap/hooks/useSwap.ts
=> fix(reverse-price-simulation): calculating proper min receive for tokenB

components/Pages/Trade/Swap/hooks/useSwap.ts, components/Pages/Trade/Swap/hooks/useTransaction.tsx
=> chore: slippage flag on osmo inj

components/AssetInput/AssetList.tsx, components/Pages/Trade/Pools/Incentives.tsx, components/Pages/Trade/Pools/IncentivesLogos.tsx
=> chore: display logo of 3 incentives

public/mainnet/columbus-5/pools_list.json
=> chore: lint

services/poolDataProvider.ts
=> feat(dashboard): readding bonding description

components/Pages/Bonding/Bonding.tsx, components/Pages/Bonding/RewardsComponent.tsx, components/Pages/Bonding/hooks/useDashboardData.ts
=> fix(bonding-apr): refactor

components/Pages/Trade/Pools/components/Liquidity.tsx, public/mainnet/migaloo-1/pools_list.json, public/mainnet/osmosis-1/pools_list.json
=> feat(roar-osmo-pool): adding pool

public/mainnet/columbus-5/pools_list.json
=> chore: readd base lunc

components/Pages/Trade/Incentivize/hooks/useIncentivePoolInfo.ts
=> fix(inj): coinhall default for inj pools

components/Wallet/Wallet.tsx, services/useAPI.ts, util/getDashboardData.ts
=> Okx chain switch

hooks/useClients.ts
=> fix: get okx direct signer

components/AssetInput/WhaleInput.tsx, components/Pages/Trade/Swap/SwapSettings.tsx, util/amountInputValidation.ts
Added validation to token input fields app-wide to improve ux.
Resolves #188  
---
=> fix: added additional validations to the WhaleInput

public/mainnet/osmosis-1/pools_list.json
=> chore: shark osmo pool

public/mainnet/migaloo-1/pools_list.json, public/mainnet/osmosis-1/pools_list.json
=> chore: pools bosmo,shark-whale

components/Wallet/Modal/WalletConnectButton.tsx, components/Wallet/Wallet.tsx, public/mainnet/migaloo-1/pools_list.json, public/mainnet/osmosis-1/pools_list.json
=> Pools: Whale-wbtc on osmo, lsdSHARK-SHARK on migaloo

public/mainnet/migaloo-1/pools_list.json
=> fix: lsd shark denom

public/mainnet/osmosis-1/pools_list.json
=> chore: lab pool

components/Pages/Trade/Pools/hooks/queryPoolInfo.ts
=> chore: enforce direct query

components/AssetInput/AssetInput.tsx, components/AssetInput/AssetList.tsx, components/AssetInput/AssetSelectModal.tsx, components/AssetInput/Input.tsx, components/AssetInput/WhaleInput.tsx, components/Pages/Trade/Incentivize/Create.tsx
=> feat: bonding assets for incentives

components/AssetInput/AssetList.tsx, components/Pages/Trade/Incentivize/hooks/useIncentivePoolInfo.ts, hooks/useTokenList.ts, public/mainnet/chihuahua-1/config.json, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/comdex-1/pools_list.json, public/mainnet/injective-1/config.json, public/mainnet/injective-1/pools_list.json, public/mainnet/juno-1/config.json, public/mainnet/juno-1/pools_list.json, public/mainnet/migaloo-1/config.json, public/mainnet/migaloo-1/pools_list.json, public/mainnet/osmosis-1/config.json, public/mainnet/phoenix-1/config.json, public/mainnet/phoenix-1/pools_list.json
=> feat: new BBL logos

components/Pages/Trade/Pools/hooks/useQueryMatchingPoolForSwap.ts
=> fix: exception on manage liquidity

components/Pages/Bonding/BondingActions/Withdraw.tsx, public/mainnet/phoenix-1/pools_list.json
=> bluna logo + nullcheck

components/Pages/Bonding/hooks/getCurrentEpoch.ts, components/Pages/Dashboard/Dashboard.tsx
=> fix: backup if data is missing

components/Pages/Dashboard/Dashboard.tsx, components/Wallet/Wallet.tsx
=> fix: disconnect on undefined wallets

hooks/useTokenList.ts
=> fix: missing info on registry result in error

components/AssetInput/AssetList.tsx, components/Pages/Trade/Pools/hooks/usePoolsListQuery.ts, hooks/usePrices.ts, hooks/useTokenList.ts, package.json
=> chore: version bump

public/mainnet/chihuahua-1/pools_list.json, public/mainnet/migaloo-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json
=> chore: add pool wind-whale migaloo

hooks/useTokenList.ts, public/mainnet/chihuahua-1/pools_list.json, public/mainnet/juno-1/pools_list.json, public/mainnet/migaloo-1/pools_list.json, public/mainnet/osmosis-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json
=> chore: add more pools

public/mainnet/chihuahua-1/pools_list.json, public/mainnet/injective-1/pools_list.json, public/mainnet/juno-1/pools_list.json
=> add gash/guppy whale/huahua pools

package.json
=> freeze inj-sdk dep

next.config.js, public/mainnet/injective-1/pools_list.json, public/mainnet/migaloo-1/pools_list.json, public/mainnet/phoenix-1/pools_list.json
=> poollist inj

public/mainnet/injective-1/pools_list.json
=> chore: update contract

constants/settings.ts, pages/[chainId]/pools/[poolId].tsx, public/mainnet/migaloo-1/pools_list.json
=> chore: add rstk-whale pool

components/Pages/Trade/Liquidity/hooks/useClaim.ts, components/Pages/Trade/Liquidity/hooks/useLiquidityAlliancePositions.ts, components/Pages/Trade/Liquidity/hooks/useRewards.ts, components/Pages/Trade/Liquidity/hooks/useStakePosition.ts, constants/tokens.ts
=> fix: claim rewards in ampluna

public/mainnet/archway-1/pools_list.json
=> adjusted arch token info

components/Pages/Trade/Pools/Pools.tsx, components/Pages/Trade/Pools/hooks/usePoolsListQuery.ts, components/Pages/Trade/Pools/hooks/useQueryPoolsLiquidity.ts, public/mainnet/phoenix-1/pools_list.json
=> aligned asset order and display name for terra assets

components/Finder.tsx, components/Pages/Trade/Liquidity/hooks/useClosePosition.ts, components/Pages/Trade/Liquidity/hooks/useLiquidityAlliancePositions.ts, components/Pages/Trade/Liquidity/hooks/useRewards.ts, components/Pages/Trade/Liquidity/hooks/useStakePosition.ts, constants/endpoints.json, constants/tokens.ts, public/mainnet/chain_info.json, public/mainnet/phoenix-1/pools_list.json
=> chore: change endpoints

public/mainnet/archway-1/pools_list.json
=> chore: add whale-arch pool archway-1

components/Pages/Flashloan/Vaults/ManagePosition/ManagePosition.tsx, components/Pages/Flashloan/Vaults/ManagePosition/WithdrawForm.tsx, components/Pages/Trade/Pools/MyPoolsTable.tsx, components/Pages/Trade/Pools/Pools.tsx, components/Pages/Trade/Pools/components/MyPosition.tsx, components/Pages/Trade/Pools/util.ts
=> added asset tooltip for my position

public/mainnet/osmosis-1/pools_list.json
=> chore: DGN-ATOM Pool

components/Pages/Trade/Pools/ActionCTAs.tsx, components/Pages/Trade/Pools/MyPoolsTable.tsx, components/Pages/Trade/Pools/Pools.tsx, components/Pages/Trade/Pools/components/MyPosition.tsx
=> improvements and fixes

util/amountInputValidation.ts
=> chore: remove trailing zeros

util/messages/createIncreaseAllowanceMessage.ts
=> fix: uint128 safety

components/Pages/Trade/Liquidity/ManageLiquidity.tsx, public/mainnet/osmosis-1/pools_list.json
=> chore: add dgn-atom incentives contract

components/Pages/Bonding/RewardsComponent.tsx, components/Pages/Dashboard/Dashboard.tsx
=> add epochs to force count

components/Pages/Trade/Liquidity/hooks/useClosePosition.ts, components/Pages/Trade/Liquidity/hooks/useLiquidityAlliancePositions.ts, components/Pages/Trade/Liquidity/hooks/useLockedPositions.ts, constants/tokens.ts, hooks/useClients.ts, hooks/useTxStatus.tsx
=> unlocking stake for terra

public/mainnet/phoenix-1/pools_list.json
=> added new pool address

public/mainnet/injective-1/pools_list.json
=> added inj pool

components/Pages/Trade/Pools/hooks/usePoolsListQuery.ts, public/mainnet/osmosis-1/pools_list.json
=> chore: dynamic incentives contract

components/AssetInput/AssetInput.tsx, components/Layout/AppLayout.tsx, components/Navbar/Navbar.tsx, components/Pages/Bonding/BondingActions/Bond.tsx, components/Pages/Bonding/BondingActions/BondingActions.tsx, components/Pages/Bonding/RewardsComponent.tsx, components/Pages/Bonding/hooks/getBonded.ts, components/Pages/Bonding/hooks/getUnbonding.ts, components/Pages/Bonding/hooks/getWithdrawable.ts, components/Pages/Bonding/hooks/useDashboardData.ts, components/Pages/Trade/Liquidity/hooks/useLockedPositions.ts, next-env.d.ts, public/mainnet/chihuahua-1/config.json, public/mainnet/columbus-5/config.json, public/mainnet/injective-1/config.json, public/mainnet/juno-1/config.json, public/mainnet/migaloo-1/config.json, public/mainnet/osmosis-1/config.json, public/mainnet/pacific-1/config.json, public/mainnet/phoenix-1/config.json
#updated bonding tokens
#enabled locked liq withdrawals
---
=> feat:liq-withdraw-and-bonding-token-update

components/Navbar/NavMenu.json, components/Navbar/Navbar.tsx, components/Navbar/NavbarPopper.tsx, components/Pages/Bonding/Bonding.tsx, components/Pages/Bonding/BondingActions/BondingActions.tsx, components/Pages/Bonding/BondingActions/hooks/useTransaction.tsx, components/Pages/Bonding/BondingOverview.tsx, components/Pages/Bonding/RewardsComponent.tsx, components/Pages/Dashboard/Dashboard.tsx, components/Pages/Trade/Pools/AllPoolsTable.tsx, components/Pages/Trade/Pools/MobilePools.tsx, components/Pages/Trade/Pools/MyPoolsTable.tsx, components/Pages/Trade/Pools/Pools.tsx, components/Pages/Trade/Pools/components/PoolName.tsx, components/Pages/Trade/Pools/types/index.ts, hooks/useClients.ts, package-lock.json, package.json, pages/[chainId]/migration.tsx, services/treasuryService.ts
=> chore: disable bonding

constants/settings.ts
=> chore: update api url

constants/settings.ts, services/treasuryService.ts
=> chore: gas adjustment
